### ISSUE TITLE
Authentication fails

### ISSUE THREAD

**Issue by foxriver76** [unknownskl/xbox-webapi-node#14]
Hey,

I am trying to perform the auth with your library, my code looks like

```javascript
        const redirectUri = apiClient._authentication.generateAuthorizationUrl();

        if (!authServerRunning) {
            authServerRunning = true;

            // looking for a free port, we prefer 8080
            const port = await adapter.getPortAsync(8080);

            adapter.log.info('Starting auth server');

            apiClient.startAuthServer(() => {
                console.log('Authentication is done. User logged in');

                apiClient.isAuthenticated().then(() =>{
                    adapter.log.warn(apiClient._authentication);
                }).catch(error => {
                    adapter.log.error(error);
                });
            }, port);
        }
```

Then I call the redirectUri and login, the Server says login successful and then the process crashes with the following error:

```

Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
--
at ServerResponse.setHeader (_http_outgoing.js:470:11)
at ServerResponse.header (/opt/iobroker/node_modules/iobroker.xbox/node_modules/express/lib/response.js:771:10)
at ServerResponse.send (/opt/iobroker/node_modules/iobroker.xbox/node_modules/express/lib/response.js:170:12)
at /opt/iobroker/node_modules/iobroker.xbox/node_modules/xbox-webapi/src/authentication.js:69:25
```

Any ideas?

**Comment by unknownskl** [comment]
Sorry for the late response. The library is kind of provided as it is. 
I looked into this problem and probably the authentication fails for some reason. Do you have a code snippet to reproduce this problem? 
It seems to be related to some external code outside of the library combined with this package.
